// Elementary Symphony — Vocabulary Data v2.0
// 5 Units x 15 Tier-2 Academic Words = 75 words total

const VOCAB_DATA = {
  units: [
    {
      id: 1, theme: "Learning and Growth Mindset", game: "Brain Builder",
      color: "#2E4057", lightColor: "#e8edf2",
      bigIdea: "Words help us describe how we think, learn, and grow through challenges.",
      essentialQuestion: "How do we talk about learning and trying hard in English?",
      storyTitle: "Maya's Big Challenge",
      story: `Maya wanted to <b>achieve</b> her dream of reading a whole book in English. It was a big <b>challenge</b>, but she decided to <b>persist</b>. Every day, she would <b>practice</b> for thirty minutes. She knew that with <b>effort</b>, she could <b>improve</b>. After each session, she would <b>reflect</b> on what she had learned. Her <b>strategy</b> was to read out loud and write new words in her notebook. Slowly, she began to see her <b>progress</b>. Maya was always <b>curious</b> about new words. She felt more <b>confident</b> every week. She loved to <b>discover</b> new stories. Her teacher said, "I <b>believe</b> in you, Maya. You will <b>succeed</b>." Maya smiled. She could feel her <b>growth</b> every single day.`,
      words: [
        { word:"achieve", pos:"verb", def:"to succeed in doing something after effort", example:"I want to achieve my goal of reading every day.", emoji:"🏆", hint1:"This word means to reach a goal after working hard.", hint2:"It starts with 'ach-' and means to reach success.", hint3:"Ach_ _ _e" },
        { word:"challenge", pos:"noun/verb", def:"something difficult that requires effort to do", example:"Learning a new language is a challenge, but I can do it.", emoji:"⛰️", hint1:"This word describes something hard that needs your best effort.", hint2:"It starts with 'ch-' and can be a noun or verb.", hint3:"Ch_ _ _ _ _ nge" },
        { word:"improve", pos:"verb", def:"to get better at something over time", example:"I improve my reading by practicing every day.", emoji:"📈", hint1:"This word means to become better at something.", hint2:"It starts with 'imp-' and is about getting better.", hint3:"Imp_ _ _e" },
        { word:"persist", pos:"verb", def:"to keep trying even when something is hard", example:"Even when the math was hard, she persisted until she understood.", emoji:"💪", hint1:"This word means to keep trying without giving up.", hint2:"It starts with 'per-' and is about not stopping.", hint3:"Per_ _ _ t" },
        { word:"reflect", pos:"verb", def:"to think carefully about something that happened", example:"After the test, I reflect on what I did well.", emoji:"🤔", hint1:"This word means to think deeply about your own learning.", hint2:"It starts with 're-' and is about thinking back.", hint3:"Re_ _ _ ct" },
        { word:"strategy", pos:"noun", def:"a plan you use to reach a goal", example:"My strategy for learning new words is to use them in sentences.", emoji:"🗺️", hint1:"This word means a smart plan you use to solve a problem.", hint2:"It starts with 'str-' and ends in '-egy'.", hint3:"Str_ _ _ _ gy" },
        { word:"effort", pos:"noun", def:"the energy and work you put into something", example:"With effort, anyone can learn something new.", emoji:"🌟", hint1:"This word describes the hard work and energy you give to a task.", hint2:"It starts with 'eff-' and is a noun.", hint3:"Eff_ _ t" },
        { word:"progress", pos:"noun", def:"movement forward or improvement over time", example:"I can see my progress when I look at my old writing.", emoji:"🚀", hint1:"This word means moving forward or getting better step by step.", hint2:"It starts with 'pro-' and ends in '-ress'.", hint3:"Pro_ _ _ ss" },
        { word:"curious", pos:"adjective", def:"eager to learn or know more about something", example:"A curious student always asks questions.", emoji:"🔍", hint1:"This word describes someone who wants to know more.", hint2:"It starts with 'cur-' and ends in '-ious'.", hint3:"Cur_ _ _ us" },
        { word:"confident", pos:"adjective", def:"feeling sure about your ability to do something", example:"She felt confident after practicing her speech many times.", emoji:"😊", hint1:"This word describes feeling sure and strong about what you can do.", hint2:"It starts with 'con-' and ends in '-dent'.", hint3:"Con_ _ _ _ nt" },
        { word:"discover", pos:"verb", def:"to find or learn something for the first time", example:"Scientists discover new things by asking questions.", emoji:"💡", hint1:"This word means to find out or learn something new for the first time.", hint2:"It starts with 'dis-' and is about finding something.", hint3:"Dis_ _ _ _ r" },
        { word:"practice", pos:"noun/verb", def:"doing something repeatedly to get better at it", example:"Daily practice helps you improve your English.", emoji:"📚", hint1:"This word means doing something again and again to get better.", hint2:"It starts with 'pra-' and ends in '-tice'.", hint3:"Pra_ _ _ ce" },
        { word:"succeed", pos:"verb", def:"to achieve a goal or do well at something", example:"You can succeed if you work hard and do not give up.", emoji:"✅", hint1:"This word means to achieve what you were trying to do.", hint2:"It starts with 'suc-' and ends in '-eed'.", hint3:"Suc_ _ _ d" },
        { word:"growth", pos:"noun", def:"the process of developing or improving", example:"Reading every day leads to growth in your vocabulary.", emoji:"🌱", hint1:"This word means the process of getting better or developing.", hint2:"It starts with 'gr-' and ends in '-wth'.", hint3:"Gr_ _ th" },
        { word:"believe", pos:"verb", def:"to feel sure that something is true or possible", example:"I believe I can learn anything if I try hard.", emoji:"⭐", hint1:"This word means to feel certain that something is true or possible.", hint2:"It starts with 'be-' and ends in '-ieve'.", hint3:"Be_ _ _ ve" }
      ]
    },
    {
      id: 2, theme: "Social Skills and Communication", game: "Team Talk",
      color: "#2D6A4F", lightColor: "#e8f4ee",
      bigIdea: "Vocabulary helps us express ourselves clearly and work well with others.",
      essentialQuestion: "How do we describe the way people communicate and cooperate in English?",
      storyTitle: "The School Project",
      story: `Our class needed to <b>communicate</b> well to finish the big project. Rajan wanted to <b>express</b> his idea about making a poster. "Let us <b>discuss</b> all our ideas," said the teacher. Everyone had an <b>opinion</b>. "I think we should make a video," said Sita. "I <b>agree</b>," said Dev. Priya said, "We must <b>respect</b> every idea." It was important to <b>listen</b> carefully to each other. When there was a <b>conflict</b> about the topic, they worked together to <b>resolve</b> it. Everyone tried to <b>contribute</b> something helpful. They learned to <b>respond</b> kindly when someone spoke. Rajan <b>shared</b> his drawing skills. They were all very <b>polite</b>. In the end, they could all <b>understand</b> each other, and the project was a great success.`,
      words: [
        { word:"communicate", pos:"verb", def:"to share ideas or feelings with others", example:"We communicate by speaking, writing, and listening.", emoji:"💬", hint1:"This word means sharing your thoughts and feelings with someone else.", hint2:"It starts with 'com-' and ends in '-ate'.", hint3:"Com_ _ _ _ _ _ te" },
        { word:"express", pos:"verb", def:"to show or say what you think or feel", example:"She expresses her feelings by writing in her journal.", emoji:"🗣️", hint1:"This word means to show what you think or feel through words.", hint2:"It starts with 'ex-' and ends in '-ess'.", hint3:"Ex_ _ _ ss" },
        { word:"cooperate", pos:"verb", def:"to work together with others toward a shared goal", example:"We cooperate as a team to finish the project.", emoji:"🤝", hint1:"This word means working together with others to get something done.", hint2:"It starts with 'co-' and ends in '-ate'.", hint3:"Co_ _ _ _ _ te" },
        { word:"respect", pos:"noun/verb", def:"showing care and consideration for others", example:"We show respect by listening when others speak.", emoji:"🙏", hint1:"This word means treating others kindly and valuing what they think.", hint2:"It starts with 're-' and ends in '-ect'.", hint3:"Re_ _ _ ct" },
        { word:"discuss", pos:"verb", def:"to talk about something with other people", example:"Let us discuss our ideas before we decide.", emoji:"💭", hint1:"This word means talking about a topic together with others.", hint2:"It starts with 'dis-' and ends in '-uss'.", hint3:"Dis_ _ ss" },
        { word:"opinion", pos:"noun", def:"what someone thinks or believes about something", example:"In my opinion, teamwork is very important.", emoji:"💡", hint1:"This word means what a person personally thinks or believes.", hint2:"It starts with 'op-' and ends in '-ion'.", hint3:"Op_ _ _ on" },
        { word:"respond", pos:"verb", def:"to reply or react to what someone says or does", example:"Please respond to my question when you are ready.", emoji:"↩️", hint1:"This word means to answer or react when someone says something.", hint2:"It starts with 're-' and ends in '-nd'.", hint3:"Re_ _ _ nd" },
        { word:"understand", pos:"verb", def:"to know the meaning of something", example:"I understand the lesson better when I ask questions.", emoji:"🧠", hint1:"This word means to know what something means or how it works.", hint2:"It starts with 'un-' and ends in '-and'.", hint3:"Un_ _ _ _ _ and" },
        { word:"contribute", pos:"verb", def:"to give something to help a group or situation", example:"Everyone can contribute an idea to make our plan better.", emoji:"🎁", hint1:"This word means to give or add something to help a group.", hint2:"It starts with 'con-' and ends in '-ute'.", hint3:"Con_ _ _ _ _ te" },
        { word:"listen", pos:"verb", def:"to pay attention to what someone is saying", example:"A good friend listens when you have a problem.", emoji:"👂", hint1:"This word means paying careful attention to what someone is saying.", hint2:"It starts with 'lis-' and ends in '-en'.", hint3:"Lis_ _ n" },
        { word:"share", pos:"verb", def:"to give part of something to others or tell others about something", example:"I like to share my ideas with my classmates.", emoji:"🤲", hint1:"This word means giving part of something to others or telling them your thoughts.", hint2:"It starts with 'sh-' and ends in '-are'.", hint3:"Sh_ _e" },
        { word:"agree", pos:"verb", def:"to have the same opinion as someone else", example:"I agree with your idea about helping the community.", emoji:"👍", hint1:"This word means thinking the same thing as someone else.", hint2:"It starts with 'ag-' and ends in '-ee'.", hint3:"Ag_ _ e" },
        { word:"polite", pos:"adjective", def:"behaving in a respectful and kind way toward others", example:"It is polite to say thank you when someone helps you.", emoji:"😊", hint1:"This word describes someone who is kind and well-mannered.", hint2:"It starts with 'po-' and ends in '-ite'.", hint3:"Po_ _ te" },
        { word:"conflict", pos:"noun", def:"a serious disagreement or problem between people", example:"We can solve a conflict by talking and listening.", emoji:"⚡", hint1:"This word means a disagreement or problem between two or more people.", hint2:"It starts with 'con-' and ends in '-ict'.", hint3:"Con_ _ _ ct" },
        { word:"resolve", pos:"verb", def:"to find a solution to a problem or conflict", example:"We worked together to resolve the disagreement.", emoji:"✅", hint1:"This word means finding a way to fix a problem or end a conflict.", hint2:"It starts with 're-' and ends in '-lve'.", hint3:"Re_ _ _ ve" }
      ]
    },
    {
      id: 3, theme: "Emotions and Character Values", game: "Character Quest",
      color: "#6B4226", lightColor: "#f4ede8",
      bigIdea: "Describing emotions and values helps us understand ourselves and others.",
      essentialQuestion: "What words do we use to describe feelings and personal character in English?",
      storyTitle: "A True Friend",
      story: `Sunita felt a strong <b>emotion</b> when she saw her friend Rina crying. She showed <b>empathy</b> by sitting beside her. Sunita was <b>grateful</b> to have a friend like Rina. She was always <b>honest</b> with her. It takes <b>courage</b> to tell the truth. Rina was very <b>patient</b> and never rushed Sunita. Both girls were <b>responsible</b> students. Sunita was also very <b>generous</b> — she always shared her lunch. She was <b>loyal</b> to her friends. When someone made a mistake, Sunita would <b>forgive</b> them quickly. She was <b>humble</b> and never boasted. Her words were always <b>sincere</b>. She was <b>determined</b> to be a good person. She tried to <b>appreciate</b> the small things in life. Rina was grateful for Sunita's <b>compassion</b>.`,
      words: [
        { word:"emotion", pos:"noun", def:"a strong feeling such as happiness, sadness, or anger", example:"Joy is an emotion I feel when I help a friend.", emoji:"❤️", hint1:"This word means a strong feeling inside you like happiness or sadness.", hint2:"It starts with 'em-' and ends in '-ion'.", hint3:"Em_ _ _ on" },
        { word:"empathy", pos:"noun", def:"understanding and sharing the feelings of another person", example:"Showing empathy means caring about how others feel.", emoji:"🫂", hint1:"This word means being able to understand what another person is feeling.", hint2:"It starts with 'em-' and ends in '-thy'.", hint3:"Em_ _ _ hy" },
        { word:"grateful", pos:"adjective", def:"feeling thankful for something good in your life", example:"I am grateful for my teachers who help me learn.", emoji:"🙏", hint1:"This word describes feeling thankful for something or someone.", hint2:"It starts with 'gra-' and ends in '-ful'.", hint3:"Gra_ _ _ ul" },
        { word:"honest", pos:"adjective", def:"telling the truth and not cheating or lying", example:"An honest person tells the truth even when it is hard.", emoji:"✅", hint1:"This word describes someone who always tells the truth.", hint2:"It starts with 'hon-' and ends in '-est'.", hint3:"Hon_ _ t" },
        { word:"patient", pos:"adjective", def:"able to wait calmly without getting upset", example:"A patient teacher explains things as many times as needed.", emoji:"⏳", hint1:"This word describes someone who can wait calmly without complaining.", hint2:"It starts with 'pat-' and ends in '-ent'.", hint3:"Pat_ _ _ t" },
        { word:"responsible", pos:"adjective", def:"doing what you are supposed to do and taking care of things", example:"A responsible student completes homework on time.", emoji:"📋", hint1:"This word describes someone who does their duties and can be trusted.", hint2:"It starts with 're-' and ends in '-ible'.", hint3:"Re_ _ _ _ _ _ ble" },
        { word:"courage", pos:"noun", def:"the strength to do something difficult or frightening", example:"It takes courage to speak in front of the class.", emoji:"🦁", hint1:"This word means being brave enough to do something scary or hard.", hint2:"It starts with 'cou-' and ends in '-age'.", hint3:"Cou_ _ _ e" },
        { word:"generous", pos:"adjective", def:"willing to give more than is expected to others", example:"A generous friend shares without being asked.", emoji:"🎁", hint1:"This word describes someone who gives freely and is kind.", hint2:"It starts with 'gen-' and ends in '-ous'.", hint3:"Gen_ _ _ us" },
        { word:"loyal", pos:"adjective", def:"staying true and supportive to someone or something", example:"A loyal friend stays by your side when things are hard.", emoji:"🛡️", hint1:"This word describes someone who supports you and never leaves your side.", hint2:"It starts with 'loy-' and ends in '-al'.", hint3:"Loy_ l" },
        { word:"forgive", pos:"verb", def:"to stop feeling angry at someone who did something wrong", example:"It is important to forgive others when they make mistakes.", emoji:"🕊️", hint1:"This word means to stop being angry at someone and give them another chance.", hint2:"It starts with 'for-' and ends in '-ive'.", hint3:"For_ _ _ e" },
        { word:"humble", pos:"adjective", def:"not thinking you are better than others; modest", example:"A humble person does not boast about their achievements.", emoji:"🌿", hint1:"This word describes someone who does not brag and stays modest.", hint2:"It starts with 'hum-' and ends in '-ble'.", hint3:"Hum_ _ e" },
        { word:"sincere", pos:"adjective", def:"truly meaning what you say; not pretending", example:"A sincere apology comes from the heart.", emoji:"💛", hint1:"This word describes someone who is genuine and really means what they say.", hint2:"It starts with 'sin-' and ends in '-ere'.", hint3:"Sin_ _ _ e" },
        { word:"determine", pos:"verb", def:"to decide firmly to do something; to have strong purpose", example:"She determined to finish the book before the weekend.", emoji:"🎯", hint1:"This word means to firmly decide to do something no matter what.", hint2:"It starts with 'det-' and ends in '-ine'.", hint3:"Det_ _ _ _ ne" },
        { word:"appreciate", pos:"verb", def:"to recognize the value of something and be thankful for it", example:"I appreciate the help my classmates give me.", emoji:"🌟", hint1:"This word means to see the value in something and feel grateful for it.", hint2:"It starts with 'app-' and ends in '-ate'.", hint3:"App_ _ _ _ _ te" },
        { word:"compassion", pos:"noun", def:"a feeling of sympathy and desire to help others who are suffering", example:"Showing compassion means caring for people who are sad or hurt.", emoji:"💗", hint1:"This word means caring about someone who is suffering and wanting to help them.", hint2:"It starts with 'com-' and ends in '-ion'.", hint3:"Com_ _ _ _ _ on" }
      ]
    },
    {
      id: 4, theme: "Community and Environment", game: "Village Builder",
      color: "#7B2D8B", lightColor: "#f3e8f5",
      bigIdea: "We need vocabulary to describe our communities and our role in protecting the environment.",
      essentialQuestion: "How do we talk about our communities and the natural world in English?",
      storyTitle: "Our Village, Our Responsibility",
      story: `Our <b>community</b> worked together to protect the <b>environment</b>. There was a big <b>pollution</b> problem in our local river. Everyone wanted to find a <b>solution</b>. The elders shared our <b>tradition</b> of caring for the land. Our <b>culture</b> teaches us to respect nature. We knew that water is a precious <b>resource</b>. We decided to <b>reduce</b> the waste we threw into the river. Every family could <b>contribute</b> in a small way. Our actions would have a big <b>impact</b>. We wanted to <b>preserve</b> the forest near our village. Some people wanted to <b>develop</b> the land, but we chose to <b>protect</b> it. Our problems are not just <b>local</b> — they are also <b>global</b>. Together, we can find good solutions for our future.`,
      words: [
        { word:"community", pos:"noun", def:"a group of people who live in the same area or share common interests", example:"Our school is an important part of our community.", emoji:"🏘️", hint1:"This word means a group of people living or working together in one place.", hint2:"It starts with 'com-' and ends in '-ity'.", hint3:"Com_ _ _ _ ty" },
        { word:"environment", pos:"noun", def:"the natural world around us, including air, water, land, and living things", example:"We must protect our environment from pollution.", emoji:"🌍", hint1:"This word means the natural world around us including forests, rivers, and air.", hint2:"It starts with 'env-' and ends in '-ment'.", hint3:"Env_ _ _ _ _ _ nt" },
        { word:"protect", pos:"verb", def:"to keep something or someone safe from harm", example:"We protect the river by not throwing rubbish in it.", emoji:"🛡️", hint1:"This word means to keep something safe and stop it from being harmed.", hint2:"It starts with 'pro-' and ends in '-ect'.", hint3:"Pro_ _ ct" },
        { word:"resource", pos:"noun", def:"something useful that people need, such as water, food, or money", example:"Water is a precious resource that we must not waste.", emoji:"💧", hint1:"This word means something valuable that people use and need to live.", hint2:"It starts with 're-' and ends in '-ource'.", hint3:"Re_ _ _ rce" },
        { word:"local", pos:"adjective", def:"belonging to or happening in a particular area near you", example:"We buy vegetables from the local market.", emoji:"📍", hint1:"This word describes something that belongs to the area near where you live.", hint2:"It starts with 'loc-' and ends in '-al'.", hint3:"Loc_ l" },
        { word:"global", pos:"adjective", def:"relating to the whole world", example:"Climate change is a global problem that affects everyone.", emoji:"🌐", hint1:"This word means something that affects or involves the whole world.", hint2:"It starts with 'glob-' and ends in '-al'.", hint3:"Glob_ l" },
        { word:"reduce", pos:"verb", def:"to make something smaller in amount or size", example:"We can reduce waste by using less plastic.", emoji:"📉", hint1:"This word means to make something less or smaller.", hint2:"It starts with 're-' and ends in '-uce'.", hint3:"Re_ _ ce" },
        { word:"pollution", pos:"noun", def:"harmful substances in the air, water, or land", example:"Pollution from factories can make rivers dirty.", emoji:"🏭", hint1:"This word means harmful waste that damages the air, water, or land.", hint2:"It starts with 'pol-' and ends in '-ion'.", hint3:"Poll_ _ _ on" },
        { word:"tradition", pos:"noun", def:"a custom or belief passed down from one generation to another", example:"Dashain is an important tradition in Nepal.", emoji:"🎋", hint1:"This word means a custom or way of doing things passed from parents to children.", hint2:"It starts with 'tra-' and ends in '-ion'.", hint3:"Trad_ _ _ on" },
        { word:"culture", pos:"noun", def:"the customs, beliefs, art, and way of life of a group of people", example:"Nepal has a rich culture with many festivals and traditions.", emoji:"🎭", hint1:"This word means the shared way of life and customs of a group of people.", hint2:"It starts with 'cul-' and ends in '-ure'.", hint3:"Cul_ _ re" },
        { word:"contribute", pos:"verb", def:"to give something to help a community or cause", example:"Students can contribute by keeping their school clean.", emoji:"🤲", hint1:"This word means to give or do something to help a group or community.", hint2:"It starts with 'con-' and ends in '-ute'.", hint3:"Con_ _ _ _ _ te" },
        { word:"impact", pos:"noun/verb", def:"the effect or influence that something has on another thing", example:"Planting trees has a positive impact on the environment.", emoji:"💥", hint1:"This word means the effect that one thing has on another.", hint2:"It starts with 'im-' and ends in '-act'.", hint3:"Im_ _ ct" },
        { word:"develop", pos:"verb", def:"to grow or cause something to grow and improve over time", example:"We need to develop better ways to manage waste.", emoji:"🌱", hint1:"This word means to grow, improve, or create something over time.", hint2:"It starts with 'dev-' and ends in '-op'.", hint3:"Dev_ _ op" },
        { word:"preserve", pos:"verb", def:"to keep something in its original state and protect it from damage", example:"We must preserve our forests for future generations.", emoji:"🌲", hint1:"This word means to protect something and keep it from being damaged.", hint2:"It starts with 'pre-' and ends in '-erve'.", hint3:"Pre_ _ _ ve" },
        { word:"solution", pos:"noun", def:"a way of solving a problem", example:"Recycling is one solution to the problem of too much waste.", emoji:"🔑", hint1:"This word means a way to fix or solve a problem.", hint2:"It starts with 'sol-' and ends in '-ion'.", hint3:"Sol_ _ _ on" }
      ]
    },
    {
      id: 5, theme: "Health and Wellbeing", game: "Wellness Journey",
      color: "#C0392B", lightColor: "#faeaea",
      bigIdea: "Knowing health vocabulary helps us describe and care for our bodies and minds.",
      essentialQuestion: "What words do we need to talk about staying healthy and feeling well in English?",
      storyTitle: "Healthy Every Day",
      story: `Good <b>nutrition</b> is one of the most important parts of staying healthy. Eating the right food gives you <b>energy</b> for school and play. Daily <b>exercise</b> keeps your body strong. There is also <b>mental</b> health to think about. Both <b>physical</b> and mental health work together. Good <b>hygiene</b>, like washing your hands, helps <b>prevent</b> illness. Having a healthy <b>routine</b> every day is a good <b>habit</b>. When you feel sick, a doctor helps you <b>recover</b>. A <b>symptom</b> like a cough tells us something might be wrong. We need to <b>maintain</b> our health by resting well. There are many <b>benefits</b> to healthy choices. Finding the right <b>balance</b> between work, rest, and play is important for <b>wellness</b>.`,
      words: [
        { word:"nutrition", pos:"noun", def:"the process of eating healthy food that your body needs", example:"Good nutrition includes eating vegetables, fruits, and grains.", emoji:"🥗", hint1:"This word is about eating the right foods to keep your body healthy.", hint2:"It starts with 'nut-' and ends in '-ion'.", hint3:"Nutr_ _ _ on" },
        { word:"exercise", pos:"noun/verb", def:"physical activity that you do to keep your body strong and healthy", example:"Running and playing sports are good forms of exercise.", emoji:"🏃", hint1:"This word means physical activity that keeps your body fit and strong.", hint2:"It starts with 'ex-' and ends in '-ise'.", hint3:"Ex_ _ _ _ se" },
        { word:"mental", pos:"adjective", def:"relating to the mind and how we think and feel", example:"Reading books is good for your mental health.", emoji:"🧠", hint1:"This word describes something related to the mind or how you think.", hint2:"It starts with 'men-' and ends in '-al'.", hint3:"Men_ al" },
        { word:"physical", pos:"adjective", def:"relating to the body and how it works", example:"Physical activity every day keeps your body strong.", emoji:"💪", hint1:"This word describes something related to the body.", hint2:"It starts with 'phy-' and ends in '-al'.", hint3:"Phy_ _ _ al" },
        { word:"prevent", pos:"verb", def:"to stop something bad from happening", example:"Washing your hands helps prevent illness.", emoji:"🛡️", hint1:"This word means to stop something bad from happening before it starts.", hint2:"It starts with 'pre-' and ends in '-ent'.", hint3:"Pre_ _ nt" },
        { word:"hygiene", pos:"noun", def:"the practice of keeping yourself clean to stay healthy", example:"Good hygiene includes washing hands and brushing teeth.", emoji:"🧼", hint1:"This word means keeping yourself clean to stay healthy.", hint2:"It starts with 'hy-' and ends in '-ene'.", hint3:"Hyg_ _ _ e" },
        { word:"energy", pos:"noun", def:"the strength and ability to be active and do things", example:"Eating breakfast gives you energy for school.", emoji:"⚡", hint1:"This word means the power and strength you need to move and work.", hint2:"It starts with 'en-' and ends in '-gy'.", hint3:"En_ _ gy" },
        { word:"balance", pos:"noun/verb", def:"a state where different things are equal or in the right proportion", example:"A healthy life needs a balance of work, rest, and play.", emoji:"⚖️", hint1:"This word means having the right amount of different things.", hint2:"It starts with 'bal-' and ends in '-ance'.", hint3:"Bal_ _ ce" },
        { word:"habit", pos:"noun", def:"something you do regularly, often without thinking about it", example:"Drinking water every morning is a healthy habit.", emoji:"🔄", hint1:"This word means something you do regularly, like a daily routine.", hint2:"It starts with 'hab-' and ends in '-it'.", hint3:"Hab_ t" },
        { word:"symptom", pos:"noun", def:"a sign that shows something is wrong with your health", example:"A sore throat is a symptom of a cold.", emoji:"🌡️", hint1:"This word means a sign or signal that something is wrong with your body.", hint2:"It starts with 'sym-' and ends in '-om'.", hint3:"Sym_ _ om" },
        { word:"recover", pos:"verb", def:"to get better after being sick or hurt", example:"With rest and medicine, she will recover from her cold.", emoji:"💊", hint1:"This word means to get better after you have been sick or injured.", hint2:"It starts with 're-' and ends in '-er'.", hint3:"Rec_ _ _ r" },
        { word:"maintain", pos:"verb", def:"to keep something in good condition by taking care of it", example:"You can maintain good health by sleeping enough.", emoji:"🔧", hint1:"This word means to keep something in good shape by looking after it.", hint2:"It starts with 'mai-' and ends in '-ain'.", hint3:"Main_ _ in" },
        { word:"benefit", pos:"noun/verb", def:"a good effect or advantage that something gives you", example:"One benefit of exercise is that it makes your heart stronger.", emoji:"✨", hint1:"This word means a good effect or advantage that you get from something.", hint2:"It starts with 'ben-' and ends in '-fit'.", hint3:"Ben_ _ it" },
        { word:"routine", pos:"noun", def:"a regular set of activities that you do at the same time each day", example:"My morning routine includes brushing my teeth and eating breakfast.", emoji:"📅", hint1:"This word means a regular set of actions you do every day.", hint2:"It starts with 'rou-' and ends in '-ine'.", hint3:"Rout_ _ e" },
        { word:"wellness", pos:"noun", def:"the state of being healthy in body and mind", example:"Wellness means taking care of both your body and your feelings.", emoji:"🌈", hint1:"This word means being healthy and feeling good in your body and mind.", hint2:"It starts with 'well-' and ends in '-ness'.", hint3:"Well_ _ ss" }
      ]
    }
  ]
};
